# Base template for cluster generation
Resources:
  @{AUTO_GENERATED_INSTANCES}
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Everywhere + SSH access via port 22 separately
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: '0'
          ToPort: '65535'
          CidrIp: 0.0.0.0/0
        