Resources:
  ZkEc2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      AWS::CloudFormation::Init:
        config: 
          packages:
            yum:
              java-1.8.0-openjdk: [] # Install Java during provisioning
          commands:
            download_zk: # download the 
              command: "wget https://www.apache.org/dyn/closer.lua/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz"
              cwd: "/home/ec2-user"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: my-key-pair
      ImageId: 'ami-0d5eff06f840b45e9' # Basic Amazon Linux without Java 
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource ZkEc2Instance '
            # - '         --configsets InstallAndRun '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0